# -*- coding: utf-8 -*-
"""Fine tunning LLMs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwJisWf673bZRt3XST74X9PPSIa02t29
"""

!pip install transformers datasets torch -q

from transformers import (
    GPT2LMHeadModel,
    GPT2Tokenizer,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)
from datasets import load_dataset # Import load_dataset
import torch
import time

print(" Libraries loaded successfully")
print(f"GPU Available: {torch.cuda.is_available()}")

model_name = "gpt2"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2LMHeadModel.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

print(f" Model loaded: GPT-2")
print(f"Total Parameters: {sum(p.numel() for p in model.parameters()):,}")

# AI/ML domain text for domain-specific fine-tuning
training_text = """
Artificial intelligence is transforming modern computing systems.
Machine learning models learn patterns from large datasets.
Natural language processing enables computers to understand text.
Deep learning uses neural networks with multiple layers.
Large language models are trained on massive text corpora.
Transformer architectures use attention mechanisms for language tasks.
GPT models generate coherent and contextually relevant text.
Fine-tuning adapts pretrained models to specific domains.
Transfer learning reduces the need for large domain datasets.
Text generation has applications in summarization and translation.
Neural networks process information through connected layers.
Attention mechanisms allow models to focus on relevant tokens.
Language models predict the next word in a sequence.
Pretraining on large corpora improves downstream task performance.
Domain adaptation improves model accuracy on specialized text.
Recurrent neural networks process sequential data over time.
BERT uses bidirectional context for language understanding.
GPT uses unidirectional autoregressive language modelling.
Tokenization converts raw text into numerical representations.
Perplexity measures how well a language model predicts text.
Overfitting occurs when a model memorizes training data.
Regularization techniques prevent overfitting in neural networks.
Batch size affects the stability of model training.
Learning rate controls how fast a model updates its weights.
Epochs refer to the number of times training data is processed.
Loss functions measure the difference between predictions and targets.
Gradient descent optimizes model parameters during training.
Backpropagation computes gradients for neural network training.
Embeddings represent words as dense numerical vectors.
Softmax converts raw scores into probability distributions.
""" * 80

with open("train.txt", "w") as f:
    f.write(training_text)

print(f" Training data created")
print(f"Total characters: {len(training_text):,}")

def generate_text(prompt, model, tokenizer, max_length=80):
    inputs = tokenizer.encode(prompt, return_tensors="pt")
    with torch.no_grad():
        outputs = model.generate(
            inputs,
            max_length=max_length,
            num_return_sequences=1,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

prompt = "Large language models are"
before_text = generate_text(prompt, model, tokenizer)
print("\n TEXT BEFORE FINE-TUNING:")
print(f"Prompt: '{prompt}'")
print(f"Generated: {before_text}")
print("\n SAVE THIS OUTPUT ")

training_args = TrainingArguments(
    output_dir="./gpt2-finetuned",
    # overwrite_output_dir=True, # Commented out due to TypeError: unexpected keyword argument
    num_train_epochs=1,
    per_device_train_batch_size=8,
    save_steps=100,
    save_total_limit=1,
    logging_steps=20,
    prediction_loss_only=True,

)

print(" Preparing dataset and initializing Trainer...")

dataset = load_dataset("text", data_files={"train": "train.txt"})

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, max_length=512)

tokenized_datasets = dataset.map(
    tokenize_function,
    batched=True,
    num_proc=4, # Use multiple processes for faster tokenization
    remove_columns=["text"]
)

block_size = 128 # Define block size for language modeling

def group_texts(examples):
    # Concatenate all texts.
    concatenated_examples = {k: sum(examples[k], []) for k in examples.keys()}
    total_length = len(concatenated_examples[list(examples.keys())[0]])
    # We drop the small remainder, we could add padding if the model supported it instead of this drop, you can
    # customize this part to your needs.
    total_length = (total_length // block_size) * block_size
    # Split by chunks of max_len.
    result = {
        k: [t[i : i + block_size] for i in range(0, total_length, block_size)]
        for k, t in concatenated_examples.items()
    }
    result["labels"] = result["input_ids"].copy()
    return result

lm_datasets = tokenized_datasets.map(
    group_texts,
    batched=True,
    batch_size=1000,
    num_proc=4,
)

train_dataset = lm_datasets["train"]

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False # Set to True for Masked Language Modeling, False for Causal LM
)

# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    data_collator=data_collator,
)

print(" Trainer initialized successfully.")

print("Starting fine-tuning...")
start_time = time.time()

train_result = trainer.train()

end_time = time.time()
training_time = round((end_time - start_time) / 60, 2)

print("\n TRAINING COMPLETE")
print("=" * 50)
print(f"Training Time: {training_time} minutes")
print(f"Final Training Loss: {train_result.training_loss:.4f}")
print(f"Total Steps: {train_result.global_step}")
print("=" * 50)
print(" SAVE THESE NUMBERS")

after_text = generate_text(prompt, model, tokenizer)
print("\n TEXT AFTER FINE-TUNING:")
print(f"Prompt: '{prompt}'")
print(f"Generated: {after_text}")
print("\n SAVE THIS OUTPUT")

print("\n" + "=" * 50)
print("RESULTS:")
print("=" * 50)
print(f"Base Model: GPT-2 (Small)")
print(f"Total Parameters:  117,000,000")
print(f"Framework: HuggingFace Transformers")
print(f"Platform: Google Colab")
print(f"Training Dataset Size: {len(train_dataset)} samples")
print(f"Epochs:  3")
print(f"Batch Size: 4")
print(f"Block Size: 64 tokens")
print(f"Optimizer: AdamW (default)")
print(f"Training Time: {training_time} minutes")
print(f"Final Loss: {train_result.training_loss:.4f}")
print(f"Before Fine-tuning: {before_text[:80]}...")
print(f"After Fine-tuning: {after_text[:80]}...")
print("=" * 50)